Fix/remote cluster
rapidsai/dask-cuda pull request #414
Opened 2020-10-09 00:14 UTC by quasiben

With this PR we fix a failure in the output of the benchmark:

Before:

```bash
(w1,w2)     | 25% 50% 75% (total nbytes)
-------------------------------
Traceback (most recent call last):
  File "local_cudf_merge.py", line 349, in <module>
    main(parse_args())
  File "local_cudf_merge.py", line 280, in main
    print(fmt % (d1, d2, bw[0], bw[1], bw[2], total_nbytes[(d1, d2)]))
TypeError: %d format: a number is required, not str
```

After:

```bash
(20200918) quasiben@DirtyHorseZ:~/Github/dask-cuda/dask_cuda/benchmarks$ python local_cudf_merge.py -c 100000 --scheduler-address 192.168.1.41:8786
Merge benchmark
-------------------------------
backend        | dask
merge type     | gpu
rows-per-chunk | 100000
protocol       | tcp
device(s)      | 0
rmm-pool       | True
frac-match     | 0.3
data-processed | 6.40 MB
===============================
Wall-clock     | Throughput
-------------------------------
79.10 ms       | 80.91 MB/s
76.30 ms       | 83.88 MB/s
75.31 ms       | 84.99 MB/s
===============================
(w1,w2)     | 25% 50% 75% (total nbytes)
-------------------------------
(tcp://192.168.1.41:35669,tcp://192.168.1.41:36401)     | 200.85 MB/s 251.42 MB/s 276.78 MB/s (72.00 MB)
(tcp://192.168.1.41:36401,tcp://192.168.1.41:35669)     | 177.83 MB/s 232.73 MB/s 285.58 MB/s (72.00 MB)
```

2020-10-09 08:38 UTC, pentschev approved these changes
Thanks for fixing this @quasiben !

2020-10-09 08:42 UTC, pentschev requested changes
Before merging I realized that seems like you were working on branch-0.17? It doesn't look like there are any changes that would change the real status of the repo, but at least the commits will look strange and I don't know if this may cause issues later in branch-0.17, see the commit list:

https://github.com/rapidsai/dask-cuda/pull/414/commits

Maybe it would be best to work on branch-0.16 and submit a new PR if we're targeting that version?

2020-10-13 12:17 UTC, quasiben commented
I changed the branch to 0.17.

2020-10-14 13:00 UTC, pentschev commented
rerun tests

2020-10-14 14:05 UTC, pentschev commented
I just realized we had to fix it for CuPy benchmarks too, I pushed the fix to your branch @quasiben , hope you don't mind.

2020-10-14 14:11 UTC, quasiben commented
not at all

2020-10-15 13:23 UTC, pentschev approved these changes
LGTM, thanks @quasiben .

2020-10-15 13:23 UTC, merged