Fix typo in benchmark utils
rapidsai/dask-cuda pull request #416
Opened 2020-10-15 13:24 UTC by quasiben

@manopapad  it looked you branched from `main`.  I cherry picked the commit and applied it to branch-0.17 for a clean commit history 

Supersedes https://github.com/rapidsai/dask-cuda/pull/415/commits/

2020-10-15 13:31 UTC, pentschev commented
Could you then do https://github.com/rapidsai/dask-cuda/pull/415#issuecomment-709320908 ?

2020-10-15 13:41 UTC, quasiben commented
> Could you then do #415 (comment) ?

Addressed in 44b8543

2020-10-19 14:33 UTC, quasiben commented
@pentschev when you have time can you give this another review ?

2020-10-19 14:43 UTC, pentschev requested changes

2020-10-19 14:43 UTC, pentschev commented on dask_cuda/benchmarks/utils.py
>          action="store_true",
```suggestion
        action="store_false",
```

2020-10-19 14:44 UTC, pentschev commented
@quasiben we want `--multi-node` to be `False` by default, added a suggestion above.

2020-10-19 14:44 UTC, quasiben commented
Dine

2020-10-19 14:47 UTC, pentschev approved these changes
Thanks @quasiben !

2020-10-19 14:53 UTC, quasiben commented
Wait, when `--multi-node` is not set it should be `False` in which case, I think we want `store_true`, right ?

2020-10-19 15:36 UTC, pentschev commented
> Wait, when `--multi-node` is not set it should be `False` in which case, I think we want `store_true`, right ?

Yes, you're right. I confused things with the whole `--enable-`/`--disable-` behavior. We do want to remove `--single-node` (and this is implicitly the default behavior), and have `--multi-node` set to `store_true`. Can you revert the latest commit?

2020-10-19 16:23 UTC, quasiben commented
Thanks for the confirmation.  Reverted the commit

2020-10-19 16:28 UTC, pentschev commented
Thanks @quasiben for noticing!

2020-10-19 17:20 UTC, merged