benchmarks: Add option to suppress output of point to point data
rapidsai/dask-cuda pull request #985
Opened 2022-08-31 15:59 UTC by wence-

When running with many workers the point to point data is not that
insightful, so add command-line flag to suppress it (default is still
to show data).

2022-08-31 16:53 UTC, pentschev requested changes
Looks good, but I think we can shorten the code quite a bit by only adding the `--no-...` option. Added suggestions for that.

2022-08-31 16:53 UTC, pentschev commented on dask_cuda/benchmarks/utils.py
> +    )
```suggestion
```

2022-08-31 16:53 UTC, pentschev commented on dask_cuda/benchmarks/utils.py
> +    )
We don't need this, just the `--no-...` option should suffice to assume the enabled option is the default (e.g., https://github.com/rapidsai/dask-cuda/blob/86a9846b1b8f1bea7bdc37c1df09a75f981f1fbf/dask_cuda/benchmarks/utils.py#L193-L197 ).

2022-08-31 16:53 UTC, pentschev commented on dask_cuda/benchmarks/utils.py
> +        dest="show_p2p_bandwidth",
```suggestion
        action="store_true",
```

2022-08-31 16:53 UTC, pentschev commented on dask_cuda/benchmarks/utils.py
> +    if args.show_p2p_bandwidth:
```suggestion
    if not args.no_show_p2p_bandwidth:
```

2022-09-01 16:35 UTC, wence- commented
> Looks good, but I think we can shorten the code quite a bit by only adding the `--no-...` option. Added suggestions for that.

Thanks, done.

2022-09-01 18:10 UTC, pentschev approved these changes
LGTM, thanks @wence- !

2022-09-01 18:11 UTC, merged